name: 'set-dnn-manifest-versions'
description: 'Sets versions in dnn manifest packages'
author: 'valadas'
inputs:
  glob:
    description: Globbing pattern to include or exclude manifests to version
    required: false
    default: '**/*.dnn'
  version:
    description: Version to set in the manifests, should be a manifest save version string as in 09.06.00
    required: true
  skipFile:
    description: A relative path (./some-folder/unversionedManifests.txt) to  text file with one glob per line of the manifest files to not update. This will update all other .dnn files not listed. When this option is used, the glob input is ignored.
    required: false
  includeSolutionInfo:
    description: When true, also sets the versions in any found SolutionInfo.cs file.
    default: 'false'
    required: false
runs:
  using: 'node12'
  main: './dist/index.js'