name: 'set-dnn-manifest-versions'
description: 'Sets versions in dnn manifest packages'
author: 'valadas'
inputs:
  glob:
    description: Globbing pattern to include or exclude manifests to version
    required: false
    default: '*.dnn'
runs:
  using: 'node12'
  main: './dist/index.js'