name: 'set-dnn-manifest-versions'
description: 'Sets versions in dnn manifest packages'
author: 'valadas'
inputs:
  glob:
    description: Globbing pattern to include or exclude manifests to version
    required: false
    default: '**/*.dnn'
  version:
    description: Version to set in the manifests, should be a manifest save version string as in 09.06.00
    required: true
  skipFile:
    description: A relative path (./some-folder/unversionedManifests.txt) to  text file with one glob per line of the manifest files to not update. This will update all other .dnn files not listed. When this option is used, the glob input is ignored.
    required: false
  includeSolutionInfo:
    description: When true, also sets the versions in any found SolutionInfo.cs file.
    default: 'false'
    required: false
  includeIssueTemplates:
    description: This option is specially meant for the Dnn.Platform repository. Upon creation of a release branch, updates the issue templates to indicate the RC version.
    required: false
    default: 'false'
  includePackageJson:
    description: If true, will update all versions of package.json
    required: false
    default: 'false'
  includeDnnReactCommon:
    description: This option is specially meant for the Dnn.Platform repository. If true, will update all references to the react common bundle too.
    required: false
    default: 'false'
runs:
  using: 'node12'
  main: './dist/index.js'